ui: mocha-qunit
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: 9..latest
  - name: safari
    version: latest
  - name: firefox
    version: latest
  - name: opera
    version: latest
